name: ci

on:
  workflow_dispatch:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    name: Check and build every extension
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false

      - uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6 # v2.2.0
        with:
          bun-version: "1.4.2"

      - name: install dependencies
        run: bun install --frozen-lockfile

      - name: format
        run: bun run format:check

      - name: lint
        run: bun run lint

      - name: type check
        run: bun run typecheck

      - name: test
        run: bun run test

      - name: build for chromium
        run: bun run build

      - name: build for firefox
        run: bun run build:firefox
